# Generated by Django 4.2.26 on 2025-12-02 08:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consommable',
            options={'verbose_name': 'Consommable', 'verbose_name_plural': 'Consommables'},
        ),
        migrations.AlterModelOptions(
            name='magasin',
            options={'verbose_name': 'Magasin', 'verbose_name_plural': 'Magasins'},
        ),
        migrations.AddField(
            model_name='consommable',
            name='seuilStockFaible',
            field=models.IntegerField(blank=True, help_text='Seuil en dessous duquel le stock est considéré comme faible', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterModelTable(
            name='portersur',
            table='gimao_porter_sur',
        ),
    ]
