# Generated by Django 4.2.26 on 2025-12-02 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donnees', '0002_alter_adresse_options_alter_document_options_and_more'),
        ('stock', '0002_alter_consommable_options_alter_magasin_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consommable',
            name='fabricant',
            field=models.ForeignKey(blank=True, help_text='Fabricant du consommable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fabricant', to='donnees.fabricant'),
        ),
        migrations.AddField(
            model_name='consommable',
            name='fournisseur',
            field=models.ForeignKey(blank=True, help_text='Fournisseur principal du consommable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fournisseur', to='donnees.fournisseur'),
        ),
    ]
