FROM node:18

WORKDIR /app

# Installer les dépendances
COPY package*.json ./
RUN npm install

# Le code source sera monté via volume pour le hot reload


EXPOSE 8080

# Dev server avec hot reload
CMD ["npm", "run", "serve", "--", "--host", "0.0.0.0"]