version: "3.9"

services:
  db-dev:
    image: mariadb:10.6
    container_name: gimao_db-dev
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: gimao
      MYSQL_USER: gimao_user
      MYSQL_PASSWORD: gimao_password
    volumes:
      - db_data_dev:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - gimao_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: gimao_phpmyadmin_dev
    environment:
      PMA_HOST: db-dev
      PMA_USER: gimao_user
      PMA_PASSWORD: gimao_password
    ports:
      - "8080:80"
    networks:
      - gimao_network
    depends_on:
      - db-dev

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: gimao_backend_dev
    volumes:
      - ./backend:/app
      - media_data_dev:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db-dev
    environment:
      - DJANGO_SETTINGS_MODULE=gimao.settings
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_EMAIL=admin@admin.com
    networks:
      - gimao_network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: gimao_frontend_dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8081:8080"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
    networks:
      - gimao_network

volumes:
  db_data_dev:
  media_data_dev:

networks:
  gimao_network:
    driver: bridge