[pytest]
DJANGO_SETTINGS_MODULE = gimao.settings_test
python_files = tests.py test_*.py *_tests.py
# Force les settings de test même si DJANGO_SETTINGS_MODULE est défini dans l'environnement du conteneur
addopts = --ds=gimao.settings_test
