# Generated by Django 4.2.26 on 2025-12-02 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-date'], 'verbose_name': 'Log', 'verbose_name_plural': 'Logs'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['rang'], 'verbose_name': 'Rôle', 'verbose_name_plural': 'Rôles'},
        ),
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'ordering': ['nomFamille', 'prenom'], 'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AlterModelTable(
            name='log',
            table='gimao_log',
        ),
        migrations.AlterModelTable(
            name='role',
            table='gimao_role',
        ),
        migrations.AlterModelTable(
            name='utilisateur',
            table='gimao_utilisateur',
        ),
        migrations.DeleteModel(
            name='Avoir',
        ),
    ]
