# Generated by Django 4.2.27 on 2025-12-14 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text="Numéro de l'adresse", max_length=10)),
                ('rue', models.CharField(help_text='Nom de la rue', max_length=255)),
                ('ville', models.CharField(help_text='Nom de la ville', max_length=100)),
                ('code_postal', models.CharField(help_text='Code postal', max_length=20)),
                ('pays', models.CharField(help_text='Nom du pays', max_length=100)),
                ('complement', models.CharField(blank=True, help_text="Complément d'adresse optionnel", max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adresses',
                'db_table': 'gimao_adresse',
            },
        ),
        migrations.CreateModel(
            name='TypeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomTypeDocument', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Type de document',
                'verbose_name_plural': 'Types de document',
                'db_table': 'gimao_type_document',
            },
        ),
        migrations.CreateModel(
            name='Lieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomLieu', models.CharField(help_text='Nom du lieu.', max_length=50)),
                ('typeLieu', models.CharField(help_text='Informations complémentaires optionnelles sur le type de lieu renseigné.', max_length=50)),
                ('lienPlan', models.CharField(blank=True, help_text='Lien vers un plan du lieu.', max_length=200, null=True)),
                ('x', models.FloatField(blank=True, help_text='Coordonnée X du lieu par rapport à son lieu parent.', null=True)),
                ('y', models.FloatField(blank=True, help_text='Coordonnée Y du lieu par rapport à son lieu parent.', null=True)),
                ('lieuParent', models.ForeignKey(blank=True, help_text="Pointeur désignant la structure (un autre lieu) où se trouve l'élément en question.", null=True, on_delete=django.db.models.deletion.CASCADE, to='donnees.lieu')),
            ],
            options={
                'verbose_name': 'Lieu',
                'verbose_name_plural': 'Lieux',
                'db_table': 'gimao_lieu',
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom du fournisseur', max_length=100)),
                ('email', models.EmailField(blank=True, help_text='Adresse email du fournisseur', max_length=191, null=True)),
                ('numTelephone', models.CharField(blank=True, help_text='Numéro de téléphone du fournisseur', max_length=20, null=True)),
                ('serviceApresVente', models.BooleanField(default=False, help_text='Indique si le fournisseur propose un service après-vente')),
                ('adresse', models.ForeignKey(blank=True, help_text='Adresse du fournisseur', null=True, on_delete=django.db.models.deletion.CASCADE, to='donnees.adresse')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'db_table': 'gimao_fournisseur',
            },
        ),
        migrations.CreateModel(
            name='Fabricant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom du fabricant', max_length=100)),
                ('email', models.EmailField(blank=True, help_text='Adresse email du fabricant', max_length=191, null=True)),
                ('numTelephone', models.CharField(blank=True, help_text='Numéro de téléphone du fabricant', max_length=20, null=True)),
                ('serviceApresVente', models.BooleanField(default=False, help_text='Indique si le fabricant propose un service après-vente')),
                ('adresse', models.ForeignKey(blank=True, help_text='Adresse du fabricant', null=True, on_delete=django.db.models.deletion.CASCADE, to='donnees.adresse')),
            ],
            options={
                'verbose_name': 'Fabricant',
                'verbose_name_plural': 'Fabricants',
                'db_table': 'gimao_fabricant',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomDocument', models.CharField(help_text='Nom du document.', max_length=100)),
                ('cheminAcces', models.CharField(help_text="Chemin d'accès au document.", max_length=200)),
                ('typeDocument', models.ForeignKey(help_text='Type du document.', on_delete=django.db.models.deletion.CASCADE, to='donnees.typedocument')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'gimao_document',
            },
        ),
    ]
