# Generated by Django 4.2.27 on 2025-12-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donnees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='cheminAcces',
            field=models.FileField(help_text="Chemin d'accès au fichier du document.", upload_to='documents/'),
        ),
    ]
