# Generated by Django 4.2.26 on 2025-12-02 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donnees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adresse',
            options={'verbose_name': 'Adresse', 'verbose_name_plural': 'Adresses'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterModelOptions(
            name='fabricant',
            options={'verbose_name': 'Fabricant', 'verbose_name_plural': 'Fabricants'},
        ),
        migrations.AlterModelOptions(
            name='fournisseur',
            options={'verbose_name': 'Fournisseur', 'verbose_name_plural': 'Fournisseurs'},
        ),
        migrations.AlterModelOptions(
            name='lieu',
            options={'verbose_name': 'Lieu', 'verbose_name_plural': 'Lieux'},
        ),
        migrations.AlterModelOptions(
            name='typedocument',
            options={'verbose_name': 'Type de document', 'verbose_name_plural': 'Types de document'},
        ),
        migrations.AlterModelTable(
            name='adresse',
            table='gimao_adresse',
        ),
        migrations.AlterModelTable(
            name='fabricant',
            table='gimao_fabricant',
        ),
        migrations.AlterModelTable(
            name='fournisseur',
            table='gimao_fournisseur',
        ),
    ]
