# Generated by Django 4.2.27 on 2025-12-02 15:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donnees', '0001_initial'),
        ('stock', '0001_initial'),
        ('utilisateur', '0001_initial'),
        ('equipement', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('contenu', models.TextField(blank=True, null=True)),
                ('compteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans_maintenance', to='equipement.compteur')),
            ],
            options={
                'verbose_name': 'Plan de maintenance',
                'verbose_name_plural': 'Plans de maintenance',
                'db_table': 'gimao_plan_maintenance',
            },
        ),
        migrations.CreateModel(
            name='TypePlanMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Type de plan de maintenance',
                'verbose_name_plural': 'Types de plan de maintenance',
                'db_table': 'gimao_type_plan_maintenance',
            },
        ),
        migrations.CreateModel(
            name='PlanMaintenanceConsommable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_necessaire', models.IntegerField(default=1, help_text='Quantité nécessaire pour ce plan', validators=[django.core.validators.MinValueValidator(1)])),
                ('consommable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.consommable')),
                ('plan_maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.planmaintenance')),
            ],
            options={
                'verbose_name': 'Consommable nécessaire',
                'verbose_name_plural': 'Consommables nécessaires',
                'db_table': 'gimao_plan_maintenance_consommable',
                'unique_together': {('plan_maintenance', 'consommable')},
            },
        ),
        migrations.AddField(
            model_name='planmaintenance',
            name='consommables',
            field=models.ManyToManyField(blank=True, related_name='plans_maintenance', through='maintenance.PlanMaintenanceConsommable', to='stock.consommable'),
        ),
        migrations.AddField(
            model_name='planmaintenance',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='plans_maintenance', to='donnees.document'),
        ),
        migrations.AddField(
            model_name='planmaintenance',
            name='equipement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans_maintenance', to='equipement.equipement'),
        ),
        migrations.AddField(
            model_name='planmaintenance',
            name='type_plan_maintenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans_maintenance', to='maintenance.typeplanmaintenance'),
        ),
        migrations.CreateModel(
            name='DemandeIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('nom', models.CharField(max_length=255)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('date_commencement', models.DateTimeField(blank=True, null=True)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_intervention', to='equipement.equipement')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_intervention', to='utilisateur.utilisateur')),
            ],
            options={
                'verbose_name': "Demande d'intervention",
                'verbose_name_plural': "Demandes d'intervention",
                'db_table': 'gimao_demande_intervention',
                'ordering': ['-date_commencement'],
            },
        ),
        migrations.CreateModel(
            name='BonTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('diagnostic', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('CORRECTIF', 'Correctif'), ('PREVENTIF', 'Préventif'), ('AMELIORATIF', 'Amélioratif')], max_length=50)),
                ('date_assignation', models.DateTimeField(blank=True, null=True)),
                ('date_cloture', models.DateTimeField(blank=True, null=True)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('date_prevue', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=50)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('commentaire_refus_cloture', models.TextField(blank=True, null=True)),
                ('demande_intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bons_travail', to='maintenance.demandeintervention')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_travail_responsable', to='utilisateur.utilisateur')),
                ('utilisateur_assigne', models.ManyToManyField(blank=True, related_name='bons_travail_assignes', to='utilisateur.utilisateur')),
            ],
            options={
                'verbose_name': 'Bon de travail',
                'verbose_name_plural': 'Bons de travail',
                'db_table': 'gimao_bon_travail',
            },
        ),
    ]
