# Generated by Django 4.2.26 on 2025-12-02 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bontravail',
            options={'verbose_name': 'Bon de travail', 'verbose_name_plural': 'Bons de travail'},
        ),
        migrations.AlterModelTable(
            name='bontravail',
            table='gimao_bon_travail',
        ),
        migrations.AlterModelTable(
            name='demandeintervention',
            table='gimao_demande_intervention',
        ),
        migrations.AlterModelTable(
            name='planmaintenance',
            table='gimao_plan_maintenance',
        ),
        migrations.AlterModelTable(
            name='planmaintenanceconsommable',
            table='gimao_plan_maintenance_consommable',
        ),
        migrations.AlterModelTable(
            name='typeplanmaintenance',
            table='gimao_type_plan_maintenance',
        ),
    ]
