# Generated by Django 4.2.27 on 2025-12-02 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0003_compteur_nomcompteur'),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bontravail',
            name='equipement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_travail', to='equipement.equipement'),
        ),
        migrations.AlterField(
            model_name='bontravail',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('EN_RETARD', 'En retard'), ('CLOTURE', 'Clôturé')], default='EN_ATTENTE', max_length=50),
        ),
    ]
