# Generated by Django 4.2.27 on 2025-12-29 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateur', '0001_initial'),
        ('donnees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomCompteur', models.CharField(default='Compteur sans nom', help_text='Nom du compteur', max_length=100)),
                ('valeurCourante', models.FloatField(help_text='Valeur actuelle du compteur')),
                ('prochaineMaintenance', models.FloatField(help_text='Valeur prévue pour la prochaine maintenance')),
                ('ecartInterventions', models.FloatField(help_text='Écart moyen entre interventions')),
                ('unite', models.CharField(default='jours', help_text='Unité de mesure du compteur', max_length=50)),
                ('estGlissant', models.BooleanField(default=False, help_text='Indique si ce compteur est glissant')),
                ('descriptifMaintenance', models.CharField(blank=True, help_text='Description de la maintenance liée', max_length=255, null=True)),
                ('necessiteHabilitationElectrique', models.BooleanField(default=False, help_text='Nécessite une habilitation électrique')),
                ('necessitePermisFeu', models.BooleanField(default=False, help_text='Nécessite un permis feu')),
                ('estPrincipal', models.BooleanField(default=False, help_text="Indique si ce compteur est le principal pour l'équipement")),
            ],
            options={
                'verbose_name': 'Compteur',
                'verbose_name_plural': 'Compteurs',
                'db_table': 'gimao_compteur',
            },
        ),
        migrations.CreateModel(
            name='Constituer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Constituer',
                'verbose_name_plural': 'Constituer',
                'db_table': 'gimao_constituer',
            },
        ),
        migrations.CreateModel(
            name='DocumentEquipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(help_text='Document associé', on_delete=django.db.models.deletion.CASCADE, to='donnees.document')),
            ],
            options={
                'verbose_name': 'Lien Document-Equipement',
                'verbose_name_plural': 'Liens Documents-Equipements',
                'db_table': 'gimao_document_equipement',
            },
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numSerie', models.CharField(help_text="Numéro de série de l'équipement", max_length=100)),
                ('reference', models.CharField(blank=True, help_text='Référence interne ou fournisseur', max_length=100, null=True)),
                ('dateCreation', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'équipement")),
                ('designation', models.CharField(help_text="Nom ou désignation de l'équipement", max_length=100)),
                ('dateMiseEnService', models.DateTimeField(blank=True, help_text="Date de mise en service de l'équipement", null=True)),
                ('prixAchat', models.DecimalField(blank=True, decimal_places=2, help_text="Prix d'achat de l'équipement", max_digits=10, null=True)),
                ('lienImage', models.FileField(blank=True, help_text="Image de l'équipement", null=True, upload_to='equipement_images/')),
                ('preventifGlissant', models.BooleanField(default=False, help_text="Indique si l'entretien préventif est glissant")),
                ('x', models.FloatField(blank=True, help_text="Coordonnée X de l'équipement dans le lieu", null=True)),
                ('y', models.FloatField(blank=True, help_text="Coordonnée Y del'équipement dans le lieu", null=True)),
                ('createurEquipement', models.ForeignKey(default=None, help_text="Utilisateur ayant créé l'équipement", on_delete=django.db.models.deletion.PROTECT, related_name='equipements_crees', to='utilisateur.utilisateur')),
                ('documents', models.ManyToManyField(blank=True, help_text="Documents associés à l'équipement", through='equipement.DocumentEquipement', to='donnees.document')),
                ('fabricant', models.ForeignKey(blank=True, help_text="Fabricant de l'équipement", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipements', to='donnees.fabricant')),
            ],
            options={
                'verbose_name': 'Équipement',
                'verbose_name_plural': 'Équipements',
                'db_table': 'gimao_equipement',
            },
        ),
        migrations.CreateModel(
            name='StatutEquipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('EN_FONCTIONNEMENT', 'En fonctionnement'), ('DEGRADE', 'Dégradé'), ('A_LARRET', "A l'arrêt"), ('HORS_SERVICE', 'Hors service')], help_text="Statut de l'équipement", max_length=50)),
                ('dateChangement', models.DateTimeField(auto_now_add=True, help_text='Date du changement de statut')),
                ('equipement', models.ForeignKey(help_text='Équipement concerné', on_delete=django.db.models.deletion.CASCADE, related_name='statuts', to='equipement.equipement')),
            ],
            options={
                'verbose_name': "Statut d'équipement",
                'verbose_name_plural': "Statuts d'équipements",
                'db_table': 'gimao_statut_equipement',
                'ordering': ['-dateChangement'],
            },
        ),
        migrations.CreateModel(
            name='ModeleEquipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Nom du modèle d'équipement", max_length=100)),
                ('fabricant', models.ForeignKey(help_text='Fabricant du modèle', on_delete=django.db.models.deletion.PROTECT, related_name='modeles', to='donnees.fabricant')),
            ],
            options={
                'verbose_name': "Modèle d'équipement",
                'verbose_name_plural': "Modèles d'équipements",
                'db_table': 'gimao_modele_equipement',
            },
        ),
        migrations.CreateModel(
            name='FamilleEquipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Nom de la famille d'équipements", max_length=100)),
                ('familleParente', models.ForeignKey(blank=True, help_text='Famille parente, si applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_familles', to='equipement.familleequipement')),
            ],
            options={
                'verbose_name': "Famille d'équipement",
                'verbose_name_plural': "Familles d'équipements",
                'db_table': 'gimao_famille_equipement',
            },
        ),
        migrations.AddField(
            model_name='equipement',
            name='famille',
            field=models.ForeignKey(blank=True, help_text="Famille de l'équipement", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipements', to='equipement.familleequipement'),
        ),
        migrations.AddField(
            model_name='equipement',
            name='fournisseur',
            field=models.ForeignKey(blank=True, help_text="Fournisseur de l'équipement", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipements', to='donnees.fournisseur'),
        ),
        migrations.AddField(
            model_name='equipement',
            name='lieu',
            field=models.ForeignKey(help_text="Lieu où se trouve l'équipement", on_delete=django.db.models.deletion.PROTECT, related_name='equipements', to='donnees.lieu'),
        ),
        migrations.AddField(
            model_name='equipement',
            name='modele',
            field=models.ForeignKey(blank=True, help_text="Modèle de l'équipement", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipements', to='equipement.modeleequipement'),
        ),
        migrations.AddField(
            model_name='documentequipement',
            name='equipement',
            field=models.ForeignKey(help_text='Équipement associé', on_delete=django.db.models.deletion.CASCADE, to='equipement.equipement'),
        ),
    ]
