# Generated by Django 4.2.26 on 2025-12-01 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donnees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeurCourante', models.FloatField(help_text='Valeur actuelle du compteur')),
                ('valeurEcheance', models.FloatField(help_text="Valeur à l'échéance pour déclencher la maintenance")),
                ('prochaineMaintenance', models.FloatField(help_text='Valeur prévue pour la prochaine maintenance')),
                ('ecartInterventions', models.FloatField(help_text='Écart moyen entre interventions')),
                ('estGlissant', models.BooleanField(default=False, help_text='Indique si ce compteur est glissant')),
                ('descriptifMaintenance', models.CharField(blank=True, help_text='Description de la maintenance liée', max_length=255, null=True)),
                ('necessiteHabilitationElectrique', models.BooleanField(default=False, help_text='Nécessite une habilitation électrique')),
                ('necessitePermisFeu', models.BooleanField(default=False, help_text='Nécessite un permis feu')),
                ('estPrincipal', models.BooleanField(default=False, help_text="Indique si ce compteur est le principal pour l'équipement")),
            ],
        ),
        migrations.CreateModel(
            name='Constituer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numSerie', models.CharField(help_text="Numéro de série de l'équipement", max_length=100)),
                ('reference', models.CharField(blank=True, help_text='Référence interne ou fournisseur', max_length=100, null=True)),
                ('dateCreation', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'équipement")),
                ('designation', models.CharField(help_text="Nom ou désignation de l'équipement", max_length=100)),
                ('dateMiseEnService', models.DateTimeField(blank=True, help_text="Date de mise en service de l'équipement", null=True)),
                ('prixAchat', models.DecimalField(blank=True, decimal_places=2, help_text="Prix d'achat de l'équipement", max_digits=10, null=True)),
                ('lienImage', models.CharField(blank=True, help_text="Lien vers une image de l'équipement", max_length=255, null=True)),
                ('preventifGlissant', models.BooleanField(default=False, help_text="Indique si l'entretien préventif est glissant")),
                ('createurEquipementId', models.IntegerField(help_text="ID de l'utilisateur ayant créé l'équipement")),
                ('x', models.FloatField(blank=True, help_text="Coordonnée X de l'équipement dans le lieu", null=True)),
                ('y', models.FloatField(blank=True, help_text="Coordonnée Y del'équipement dans le lieu", null=True)),
                ('documents', models.ManyToManyField(blank=True, help_text="Documents associés à l'équipement", to='donnees.document')),
            ],
        ),
        migrations.CreateModel(
            name='StatutEquipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(help_text="Statut de l'équipement", max_length=50)),
                ('dateChangement', models.DateTimeField(auto_now_add=True, help_text='Date du changement de statut')),
                ('equipement', models.ForeignKey(help_text='Équipement concerné', on_delete=django.db.models.deletion.CASCADE, related_name='statuts', to='equipement.equipement')),
            ],
        ),
        migrations.CreateModel(
            name='ModeleEquipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Nom du modèle d'équipement", max_length=100)),
                ('fabricant', models.ForeignKey(help_text='Fabricant du modèle', on_delete=django.db.models.deletion.PROTECT, related_name='modeles', to='donnees.fabricant')),
            ],
        ),
        migrations.CreateModel(
            name='FamilleEquipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Nom de la famille d'équipements", max_length=100)),
                ('familleParente', models.ForeignKey(blank=True, help_text='Famille parente, si applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_familles', to='equipement.familleequipement')),
            ],
        ),
        migrations.AddField(
            model_name='equipement',
            name='famille',
            field=models.ForeignKey(blank=True, help_text="Famille de l'équipement", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipements', to='equipement.familleequipement'),
        ),
        migrations.AddField(
            model_name='equipement',
            name='lieu',
            field=models.ForeignKey(help_text="Lieu où se trouve l'équipement", on_delete=django.db.models.deletion.PROTECT, related_name='equipements', to='donnees.lieu'),
        ),
        migrations.AddField(
            model_name='equipement',
            name='modele',
            field=models.ForeignKey(help_text="Modèle de l'équipement", on_delete=django.db.models.deletion.PROTECT, related_name='equipements', to='equipement.modeleequipement'),
        ),
    ]
