# Generated by Django 4.2.27 on 2025-12-14 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipement', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituer',
            name='consommable',
            field=models.ForeignKey(help_text='Consommable associé', on_delete=django.db.models.deletion.CASCADE, to='stock.consommable'),
        ),
        migrations.AddField(
            model_name='constituer',
            name='equipement',
            field=models.ForeignKey(help_text='Équipement associé', on_delete=django.db.models.deletion.CASCADE, to='equipement.equipement'),
        ),
        migrations.AddField(
            model_name='compteur',
            name='equipement',
            field=models.ForeignKey(help_text='Équipement associé au compteur', on_delete=django.db.models.deletion.CASCADE, related_name='compteurs', to='equipement.equipement'),
        ),
    ]
