# Generated by Django 4.2.27 on 2026-01-16 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
        ('maintenance', '0001_initial'),
        ('equipement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='declencher',
            name='planMaintenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='declenchements', to='maintenance.planmaintenance'),
        ),
        migrations.AddField(
            model_name='constituer',
            name='consommable',
            field=models.ForeignKey(help_text='Consommable associé', on_delete=django.db.models.deletion.CASCADE, to='stock.consommable'),
        ),
        migrations.AddField(
            model_name='constituer',
            name='equipement',
            field=models.ForeignKey(help_text='Équipement associé', on_delete=django.db.models.deletion.CASCADE, to='equipement.equipement'),
        ),
        migrations.AddField(
            model_name='compteur',
            name='equipement',
            field=models.ForeignKey(help_text='Équipement associé au compteur', on_delete=django.db.models.deletion.CASCADE, related_name='compteurs', to='equipement.equipement'),
        ),
        migrations.AddConstraint(
            model_name='declencher',
            constraint=models.UniqueConstraint(fields=('compteur', 'planMaintenance'), name='unique_declenchement_compteur_valeur'),
        ),
    ]
