# Generated by Django 4.2.27 on 2025-12-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compteur',
            name='nomCompteur',
            field=models.CharField(default='Compteur sans nom', help_text='Nom du compteur', max_length=100),
        ),
    ]
