# Generated by Django 4.2.27 on 2025-12-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='lienImage',
            field=models.FileField(blank=True, help_text="Image de l'équipement", null=True, upload_to='equipement_images/'),
        ),
    ]
