# Generated by Django 4.2.26 on 2025-12-02 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compteur',
            options={'verbose_name': 'Compteur', 'verbose_name_plural': 'Compteurs'},
        ),
        migrations.AlterModelOptions(
            name='constituer',
            options={'verbose_name': 'Constituer', 'verbose_name_plural': 'Constituer'},
        ),
        migrations.AlterModelOptions(
            name='equipement',
            options={'verbose_name': 'Équipement', 'verbose_name_plural': 'Équipements'},
        ),
        migrations.AlterModelOptions(
            name='familleequipement',
            options={'verbose_name': "Famille d'équipement", 'verbose_name_plural': "Familles d'équipements"},
        ),
        migrations.AlterModelOptions(
            name='modeleequipement',
            options={'verbose_name': "Modèle d'équipement", 'verbose_name_plural': "Modèles d'équipements"},
        ),
        migrations.AlterModelOptions(
            name='statutequipement',
            options={'ordering': ['-dateChangement'], 'verbose_name': "Statut d'équipement", 'verbose_name_plural': "Statuts d'équipements"},
        ),
        migrations.AlterModelTable(
            name='compteur',
            table='gimao_compteur',
        ),
        migrations.AlterModelTable(
            name='constituer',
            table='gimao_constituer',
        ),
        migrations.AlterModelTable(
            name='equipement',
            table='gimao_equipement',
        ),
        migrations.AlterModelTable(
            name='familleequipement',
            table='gimao_famille_equipement',
        ),
        migrations.AlterModelTable(
            name='modeleequipement',
            table='gimao_modele_equipement',
        ),
        migrations.AlterModelTable(
            name='statutequipement',
            table='gimao_statut_equipement',
        ),
    ]
