# Generated by Django 4.2.27 on 2025-12-31 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compteur',
            name='derniereIntervention',
            field=models.IntegerField(default=0, help_text='Valeur du compteur à la dernière intervention effectuée'),
        ),
    ]
