# Generated by Django 4.2.27 on 2025-12-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0003_alter_equipement_lienimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statutequipement',
            name='statut',
            field=models.CharField(choices=[('EN_FONCTIONNEMENT', 'En fonctionnement'), ('DEGRADE', 'Dégradé'), ('A_LARRET', 'En maintenance'), ('HORS_SERVICE', 'Hors service')], help_text="Statut de l'équipement", max_length=50),
        ),
    ]
