# Generated by Django 4.2.26 on 2025-12-02 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donnees', '0002_alter_adresse_options_alter_document_options_and_more'),
        ('equipement', '0003_alter_compteur_options_alter_constituer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentEquipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(help_text='Document associé', on_delete=django.db.models.deletion.CASCADE, to='donnees.document')),
                ('equipement', models.ForeignKey(help_text='Équipement associé', on_delete=django.db.models.deletion.CASCADE, to='equipement.equipement')),
            ],
            options={
                'verbose_name': 'Lien Document-Equipement',
                'verbose_name_plural': 'Liens Documents-Equipements',
                'db_table': 'gimao_document_equipement',
            },
        ),
    ]
