# Generated by Django 4.2.27 on 2026-01-01 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
        ('equipement', '0003_compteur_derniereintervention'),
    ]

    operations = [
        migrations.AddField(
            model_name='compteur',
            name='planMaitenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan_maintenance_compteur', to='maintenance.planmaintenance'),
        ),
    ]
