# Generated by Django 4.2.26 on 2025-12-03 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donnees', '0001_initial'),
        ('equipement', '0003_compteur_nomcompteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='fabricant',
            field=models.ForeignKey(blank=True, help_text="Fabricant de l'équipement", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipements', to='donnees.fabricant'),
        ),
        migrations.AddField(
            model_name='equipement',
            name='fournisseur',
            field=models.ForeignKey(blank=True, help_text="Fournisseur de l'équipement", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipements', to='donnees.fournisseur'),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='modele',
            field=models.ForeignKey(blank=True, help_text="Modèle de l'équipement", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipements', to='equipement.modeleequipement'),
        ),
    ]
