# Generated by Django 4.2.27 on 2025-12-13 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
        ('equipement', '0004_equipement_fabricant_equipement_fournisseur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipement',
            name='createurEquipementId',
        ),
        migrations.AddField(
            model_name='equipement',
            name='createurEquipement',
            field=models.ForeignKey(default=None, help_text="Utilisateur ayant créé l'équipement", on_delete=django.db.models.deletion.PROTECT, related_name='equipements_crees', to='utilisateur.utilisateur'),
        ),
    ]
