# Generated by Django 4.2.27 on 2026-01-01 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0004_compteur_planmaitenance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compteur',
            old_name='planMaitenance',
            new_name='planMaintenance',
        ),
    ]
