# Generated by Django 4.2.27 on 2025-12-13 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0005_remove_equipement_createurequipementid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compteur',
            name='valeurEcheance',
        ),
    ]
