# Generated by Django 4.2.27 on 2025-12-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0006_remove_compteur_valeurecheance'),
    ]

    operations = [
        migrations.AddField(
            model_name='compteur',
            name='unite',
            field=models.CharField(default='jours', help_text='Unité de mesure du compteur', max_length=50),
        ),
    ]
